### ISSUE TITLE
Ways to not have AWS credentials in fleet units

### ISSUE THREAD

**Issue by grepory** [coreos/elb-presence#12]
I use elb-presence for ELB membership with Fleet units, as one does.

In order to do this, I have to have AWS credentials in my fleet units or I have to have static credentials in an EnvironmentFile. What I would like to do is get credentials (at request time) from a credential chain, like I would in a Go or Java equivalent of elb-presence.

I have created an [issue in boto3](https://github.com/boto/boto3/issues/222), but that is probably more effort than simply re-implementing elb-presence in Go (which is my current plan). Do you have any other suggestions besides my current plan?

**Comment by grepory** [comment]
TIL, boto3 supports credentials from IAM roles. So I will figure out how to maybe do that, if that's even possible.

**Comment by aggronerd** [comment]
Hi grepory, I've managed to do this before but I had to change the code so that if you don't provide the authentication parameters specified in the readme it falls back to Boto using IAM. My PR is here if you want to take a look https://github.com/coreos/elb-presence/pull/11

**Comment by grepory** [comment]
Fantastic, thanks! I'll give it a look today.
