### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'register_instances'

### ISSUE THREAD

**Issue by stephennancekivell** [coreos/elb-presence#7]
There seems to be a bug in the python script. This could be a bug in the library im not sure, but I get this.
```
File "/bin/elb-presence", line 28, in <module>
conn.register_instances(args.lbname, [instance])
AttributeError: 'NoneType' object has no attribute 'register_instances'
```

Im following the example here, but with my own simple web server.
https://coreos.com/docs/launching-containers/launching/fleet-example-deployment/

Thanks

**Comment by eugeneware** [comment]
Yeah, I'm getting the same thing.

**Comment by bcwaldon** [comment]
Can you verify that you are properly configuring your AWS creds? We should clearly check for None here before proceeding in the code - could you get a patch together for that?

**Comment by jaykay** [comment]
Has anyone got clues for that? I'm stuck at the exact same point. I'm trying to connect to a loadbalancer in Frankfurt (eu-central-1) and many older libraries have issues with this, so I thought perhaps the "official coreos way" would do... But it don't.

**Comment by fragtom** [comment]
The reason is in python library boto 2.21 - that doesn't support eu-central-1. Update to boto >= 2.35 works.. see https://github.com/boto/boto/issues/2835

**Comment by fragtom** [comment]
I've fixed installation with "pip boto" on own Dockerfile 
https://registry.hub.docker.com/u/organizeme/elb-presence/
